# [START app_yaml]
runtime: nodejs18

# optional stuff

instance_class: F2

env_variables:
  DATABASE: "mongodb+srv://thisisgeniusguy:myvenue0601@venue-main.ketzrpm.mongodb.net/myvenue-room'"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto